name: Update Readme time stats

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme time stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}  # 使用 PAT 而不是默认的 GITHUB_TOKEN！！！！！

      - name: Update README with current time
        run: |
          sed -i '$ d' README.md
          echo -e "Last updated: $(date +'%Y-%m-%d')" >> README.md

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Updated README with current time" || exit 0  # Exit gracefully if no changes
          git push https://${{ secrets.PAT }}@github.com/herbertskyper/herbertskyper.git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}